name: Deploy Frontend to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: tech0gen8posregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and Push Docker image
      run: |
        docker build -t tech0gen8posregistry.azurecr.io/frontend:${{ github.sha }} .
        docker push tech0gen8posregistry.azurecr.io/frontend:${{ github.sha }}
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tech0-gen8-step4-pos-app-77'
        images: 'tech0gen8posregistry.azurecr.io/frontend:${{ github.sha }}' 