name: Deploy Frontend to Azure

# Workflow for deploying frontend to Azure Web App
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pos-frontend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/pos-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_API_URL=https://tech0-gen8-step4-pos-app-78.azurewebsites.net
      
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech0-gen8-step4-pos-app-77'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ github.repository_owner }}/pos-frontend:${{ github.sha }}'
          
      - name: Azure App Service Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'tech0-gen8-step4-pos-app-77'
          app-settings-json: |
            [
              {
                "name": "WEBSITES_PORT",
                "value": "3000"
              },
              {
                "name": "NEXT_PUBLIC_API_URL",
                "value": "https://tech0-gen8-step4-pos-app-78.azurewebsites.net"
              }
            ]