name: tech0-gen8-step4-pos-app-77
runtime: NODE|18-lts
env:
  - name: NEXT_PUBLIC_API_URL
    value: https://tech0-gen8-step4-pos-app-78.azurewebsites.net/api
  - name: NODE_ENV
    value: production 